name: "multi-event-pipeline"

on:
  push:
    branches:
      - master

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "running the master push"
        run: echo "Running on master push"