name: "multi-event-pipeline"

on:
  push:
    
    branches:
      - master
  pull_request:
    types:
        - opened
        - closed
    branches:
      - master
          

jobs:
  on-push:
    if: github.event_name =='push' 
    runs-on: ubuntu-latest
    steps:
      - name: "running the master push"
        run: echo "Running on master push"
      - name: "date is:"
        run: date

  on-pull-request:
    if : github.event_name =='pull_request' 
    runs-on: ubuntu-latest
    steps:
      - name: "opened PR"
        if: github.event.action =='opened'
        run: echo "Pull request was opened" date
      - name: "closed PR" 
        if: github.event.action =='closed'
        run: echo "Pull request was closed on date $(date)" 
       
      
      
      
       