name: "multi-event-pipeline"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
          

jobs:
  on-push:
    if: github.event_name =='push' 
    runs-on: ubuntu-latest
    steps:
      - name: "running the master push"
        run: echo "Running on master push"
      - name: "date is:"
        run: date

  on-pull_request:
    if : github.event_name =='pull_request' 
    runs-on: ubuntu-latest
    steps:
      - name: "running the master push"
        run: echo "Running on master push"
      - name: "date is:"
        run: date